[versions]
kotlin = "2.1.10"
rdGen = "2025.2.2"
riderSdk = "2025.2"
riderSdkPreview = "2025.2"

[libraries]
bson4Jackson = "de.undercouch:bson4jackson:2.18.0"
junit = "junit:junit:4.13.2"
kotlinStdLib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
openTest4J = "org.opentest4j:opentest4j:1.3.0"
rdGen = { group = "com.jetbrains.rd", name = "rd-gen", version.ref = "rdGen" }

[plugins]
changelog = "org.jetbrains.changelog:2.4.0"
gradleJvmWrapper = "me.filippov.gradle.jvm.wrapper:0.15.0"
intelliJPlatform = "org.jetbrains.intellij.platform:2.7.2"
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
