[versions]
kotlin = "2.1.10"
rdGen = "2025.1.1"
riderSdk = "2025.2-EAP5-SNAPSHOT"
riderSdkPreview = "2025.2-EAP5-SNAPSHOT"

[libraries]
bson4Jackson = "de.undercouch:bson4jackson:2.18.0"
kotlinStdLib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
openTest4J = "org.opentest4j:opentest4j:1.3.0"
rdGen = { group = "com.jetbrains.rd", name = "rd-gen", version.ref = "rdGen" }

[plugins]
changelog = "org.jetbrains.changelog:2.2.1"
gradleJvmWrapper = "me.filippov.gradle.jvm.wrapper:0.14.0"
intelliJPlatform = "org.jetbrains.intellij.platform:2.6.0"
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
