name: "Dependency Checker"
on:
  schedule:
    - cron: '0 0 * * *' # Every day
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - name: "Check out the sources"
        uses: actions/checkout@v6

      - id: update
        uses: ForNeVeR/intellij-updater@v1
        name: "Update the dependency versions"

      - if: steps.update.outputs.has-changes == 'true' && (github.event_name == 'schedule' || github.event_name == 'workflow_dispatch')
        uses: actions/create-github-app-token@v2
        id: generate-token
        with:
          app-id: ${{ secrets.IJ_UPDATER_APP_ID }}
          private-key: ${{ secrets.IJ_UPDATER_PRIVATE_KEY }}

      - if: steps.update.outputs.has-changes == 'true' && (github.event_name == 'schedule' || github.event_name == 'workflow_dispatch')
        name: "Create a PR"
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ steps.generate-token.outputs.token }}
          branch: ${{ steps.update.outputs.branch-name }}
          author: "AvaloniaRider automation <friedrich@fornever.me>"
          commit-message: ${{ steps.update.outputs.commit-message }}
          title: ${{ steps.update.outputs.pr-title }}
          body-path: ${{ steps.update.outputs.pr-body-path }}
